dataConnectors:
- host: $webServerHost
  id: 1
  implementation: net/http
  name: WebServer
  port: $webServerPort
  programmingLanguage: 1
  type: 1
- id: 2
  implementation: function
  name: OutputDataConnector
  programmingLanguage: 0
  type: 4
endpoints:
- format: json
  id: 1
  idDataConnector: 1
  method: POST
  name: InputTextEndpoint
  path: /text
- delay: 0
  functionName: OutputWordEndpointFunc
  functionPackage: ""
  id: 2
  idDataConnector: 2
  name: OutputWordEndpoint
  publicFunction: false
- delay: 0
  functionName: OutputCharEndpointFunc
  functionPackage: ""
  id: 3
  idDataConnector: 2
  name: OutputCharEndpoint
  publicFunction: false
links:
- callSemantics: 1
  from: 1
  inheritedCallSemantics: true
  to: 2
- callSemantics: 1
  from: 2
  inheritedCallSemantics: true
  to: 3
- callSemantics: 1
  from: 3
  inheritedCallSemantics: true
  to: 4
- callSemantics: 1
  from: 4
  inheritedCallSemantics: true
  to: 5
- callSemantics: 1
  communicationProtocol: 2
  from: 3
  inheritedCallSemantics: true
  methodName: SplitToSplitword
  timeout: 0
  to: 6
- callSemantics: 1
  from: 6
  inheritedCallSemantics: true
  to: 7
services:
- color: '#D7FFD2'
  defaultCallSemantics: 1
  defaultGrpcTimeout: 0
  delayExecutors: 1
  environment: ""
  grpcHost: $wordsProcessorGrpcHost
  grpcPort: $wordsProcessorGrpcPort
  id: 1
  metricsEngine: 1
  monitoringHost: $wordsProcessorMonitoringHost
  monitoringPort: $wordsProcessorMonitoringPort
  name: WordsProcessor
  programmingLanguage: 1
  shutdownTimeout: 30000
- color: '#D2E5FF'
  defaultCallSemantics: 1
  defaultGrpcTimeout: 0
  delayExecutors: 1
  environment: ""
  grpcHost: $charsProcessorGrpcHost
  grpcPort: $charsProcessorGrpcPort
  id: 2
  metricsEngine: 1
  monitoringHost: $charsProcessorMonitoringHost
  monitoringPort: $charsProcessorMonitoringPort
  name: CharsProcessor
  programmingLanguage: 1
  shutdownTimeout: 30000
settings:
  golangVersion: 1.22.3
  modulePath: example.com
  name: TextProcessor
streams:
- id: 1
  idEndpoint: 1
  idService: 1
  idSource: 0
  idSources: []
  name: InputText
  type: 1
  valueType: TextData
  xPos: 71
  yPos: -86
- functionName: SplitTextFunc
  functionPackage: ""
  id: 2
  idService: 1
  idSource: 1
  idSources: []
  name: SplitText
  publicFunction: false
  type: 7
  valueType: Word
  xPos: 69
  yPos: 19
- id: 3
  idService: 1
  idSource: 2
  idSources: []
  name: Split
  type: 11
  xPos: 68
  yPos: 134
- functionName: FilterWordFunc
  functionPackage: ""
  id: 4
  idService: 1
  idSource: 3
  idSources: []
  name: FilterWord
  publicFunction: false
  type: 3
  xPos: 74
  yPos: 236
- id: 5
  idEndpoint: 2
  idService: 1
  idSource: 4
  idSources: []
  name: OutputWord
  type: 13
  xPos: 78
  yPos: 336
- id: 6
  idService: 2
  idSource: 3
  idSources: []
  name: SplitWord
  type: 8
  valueType: Char
  xPos: 316
  yPos: 136
- id: 7
  idEndpoint: 3
  idService: 2
  idSource: 6
  idSources: []
  name: OutputChar
  type: 13
  xPos: 580
  yPos: 136
types:
- name: Map1ValueType
  publicType: false
  type: int
  useAlias: false
- definitionFormat: 2
  name: TextData
  package: ""
  publicType: false
  transferByValue: false
  type: struct
- name: Map2ValueType
  publicType: false
  type: int
  useAlias: false
- name: Word
  publicType: false
  type: string
  useAlias: false
- name: Map3ValueType
  publicType: false
  type: int
  useAlias: false
- name: Map4ValueType
  publicType: false
  type: int
  useAlias: false
- name: Map5ValueType
  publicType: false
  type: int
  useAlias: false
- name: Map6ValueType
  publicType: false
  type: int
  useAlias: false
- name: Char
  publicType: false
  type: char
  useAlias: false
- name: Map7ValueType
  publicType: false
  type: int
  useAlias: false
- name: Map8ValueType
  publicType: false
  type: int
  useAlias: false
- name: Parallels8ValueType
  publicType: false
  type: int
  useAlias: false
